-- V1__init.sql — 월급 배분 관리 서비스 초기 스키마 (ERD.md v1.2, 11테이블)
-- 정본: docs/ERD.md. 금액은 bigint 원 단위(double 금지). 비즈니스 날짜는 date(KST 판정),
-- 저장 시각은 timestamptz. enum류는 varchar(애플리케이션/구조화 데이터로 강제).
-- 마이그레이션 불변: 이 파일은 수정 금지 — 변경은 새 V{n} 추가로만(ADR-08).

-- ── users — 사용자 ────────────────────────────────────────────────
create table users (
    id                                  bigint generated by default as identity primary key,
    provider                            varchar(20)  not null,                 -- KAKAO / GOOGLE / NAVER
    provider_id                         varchar(255) not null,
    email                               varchar(255),
    nickname                            varchar(50)  not null,
    base_income                         bigint       not null,                 -- 평소 실수령액(원)
    payday                              smallint     not null,                 -- 1~31, 없는 달은 말일
    payday_adjustment                   varchar(20)  not null,                 -- PREV_BUSINESS_DAY / NEXT_BUSINESS_DAY / NONE
    include_investment_in_savings_rate  boolean      not null default true,
    locale                              varchar(5)   not null default 'ko',
    living_account_id                   bigint,                                -- FK→accounts (아래 ALTER, 순환 참조 해소)
    created_at                          timestamptz  not null default now(),
    constraint uq_users_provider unique (provider, provider_id)
);

-- ── accounts — 통장 (계좌번호 등 금융 식별 정보 저장 금지) ─────────────
create table accounts (
    id              bigint generated by default as identity primary key,
    user_id         bigint       not null references users (id) on delete cascade,
    name            varchar(50)  not null,                                     -- 별칭(예: 케이뱅크)
    purpose         varchar(100),
    bank_deep_link  varchar(500),
    sort_order      int          not null,
    is_active       boolean      not null default true                         -- soft delete
);
create index idx_accounts_user on accounts (user_id);

-- users.living_account_id → accounts (순환 FK라 테이블 생성 후 추가)
alter table users
    add constraint fk_users_living_account
    foreign key (living_account_id) references accounts (id) on delete set null;

-- ── budget_items — 배분 항목 ──────────────────────────────────────
create table budget_items (
    id                         bigint generated by default as identity primary key,
    user_id                    bigint       not null references users (id) on delete cascade,
    account_id                 bigint       not null references accounts (id) on delete cascade,
    category                   varchar(20)  not null,                          -- SAVING/INVESTMENT/FIXED/INSURANCE/SUBSCRIPTION/EMERGENCY
    name                       varchar(50)  not null,
    amount                     bigint       not null,                          -- 월 환산 금액(원)
    input_cycle                varchar(10)  not null default 'MONTHLY',        -- MONTHLY / DAILY
    input_meta                 jsonb,                                          -- 원본 입력 보존(일 금액·통화·환율·버퍼)
    start_date                 date         not null,
    end_date                   date,                                           -- 만기일
    interest_rate              numeric(5, 2),                                  -- 연이율(%)
    tax_type                   varchar(20),                                    -- NORMAL / PREFERENTIAL / TAX_FREE
    expected_maturity_amount   bigint,                                         -- 수동 입력값(있으면 공식 대신)
    maturity_actual_amount     bigint,
    memo                       text,
    sort_order                 int          not null,
    status                     varchar(20)  not null,                          -- ACTIVE / ARCHIVED / DELETED
    created_at                 timestamptz  not null default now(),
    updated_at                 timestamptz  not null default now()
);
create index idx_budget_items_user_status on budget_items (user_id, status);

-- ── envelopes — 봉투 ──────────────────────────────────────────────
create table envelopes (
    id             bigint generated by default as identity primary key,
    user_id        bigint       not null references users (id) on delete cascade,
    account_id     bigint       not null references accounts (id) on delete cascade,
    name           varchar(50)  not null,
    target_amount  bigint       not null,
    saved_amount   bigint       not null default 0,                            -- 트랜잭션 합계 캐시
    next_due_date  date         not null,
    cycle_months   smallint,                                                   -- NULL = 일회성
    memo           text,
    status         varchar(20)  not null,                                      -- ACTIVE / CLOSED / DELETED
    created_at     timestamptz  not null default now()
);
create index idx_envelopes_user_status on envelopes (user_id, status);

-- ── envelope_transactions — 봉투 적립/지출 기록 ───────────────────────
create table envelope_transactions (
    id                bigint generated by default as identity primary key,
    envelope_id       bigint       not null references envelopes (id) on delete cascade,
    type              varchar(10)  not null,                                   -- DEPOSIT / SPEND
    amount            bigint       not null,                                   -- 계획 금액
    actual_amount     bigint,                                                  -- SPEND 실제 지출액
    shortfall_source  varchar(20),                                             -- LIVING / EMERGENCY
    carry_over        boolean,
    cycle_id          bigint,                                                  -- FK→cycles (아래 ALTER)
    occurred_on       date         not null,
    created_at        timestamptz  not null default now()
);
create index idx_envelope_tx_envelope on envelope_transactions (envelope_id);

-- ── cycles — 사이클(월 계획 스냅샷) ───────────────────────────────────
create table cycles (
    id                bigint generated by default as identity primary key,
    user_id           bigint       not null references users (id) on delete cascade,
    cycle_start       date         not null,                                   -- 실제 지급일(조정 반영)
    cycle_end         date         not null,                                   -- 다음 지급일 전날
    label             varchar(10)  not null,                                   -- 시작 월 기준(예: 2026-06)
    income            bigint       not null,
    income_confirmed  boolean      not null default false,
    created_at        timestamptz  not null default now(),
    constraint uq_cycles_user_start unique (user_id, cycle_start)              -- 스냅샷 멱등(NFR-05)
);

-- envelope_transactions.cycle_id → cycles (cycles 생성 후 추가)
alter table envelope_transactions
    add constraint fk_envelope_tx_cycle
    foreign key (cycle_id) references cycles (id) on delete set null;

-- ── plan_lines — 사이클 배분 라인 (값 복사로 역사 불변) ─────────────────
create table plan_lines (
    id                      bigint generated by default as identity primary key,
    cycle_id                bigint       not null references cycles (id) on delete cascade,
    line_type               varchar(10)  not null,                             -- ITEM / ENVELOPE / LIVING / EXTRA
    budget_item_id          bigint       references budget_items (id) on delete set null,
    envelope_id             bigint       references envelopes (id) on delete set null,
    account_id              bigint       references accounts (id) on delete set null,  -- 체크리스트 group by 기준
    name_snapshot           varchar(50)  not null,
    category_snapshot       varchar(20)  not null,
    account_name_snapshot   varchar(50)  not null,
    planned_amount          bigint       not null,
    status                  varchar(10)  not null,                             -- PENDING / DONE / SKIPPED
    checked_at              timestamptz
);
create index idx_plan_lines_cycle on plan_lines (cycle_id);

-- ── check_ins — 월말 체크인 (사이클당 1건) ────────────────────────────
create table check_ins (
    id                bigint generated by default as identity primary key,
    cycle_id          bigint       not null references cycles (id) on delete cascade,
    living_remaining  bigint       not null,                                   -- 입력: 생활비 통장 잔액
    topped_up         bigint       not null default 0,                         -- 입력: 추가 투입액
    overspend         bigint       not null,                                   -- 계산: topped_up − living_remaining
    note              text,
    created_at        timestamptz  not null default now(),
    constraint uq_check_ins_cycle unique (cycle_id)
);

-- ── suggestions — 보정/리밸런싱 제안 ─────────────────────────────────
create table suggestions (
    id           bigint generated by default as identity primary key,
    user_id      bigint       not null references users (id) on delete cascade,
    type         varchar(30)  not null,                                        -- RAISE_LIVING / REBALANCE_MATURITY / WINDFALL ...
    payload      jsonb        not null,                                        -- 구조화 파라미터(문장은 클라이언트 조립)
    status       varchar(10)  not null,                                        -- PENDING / APPLIED / DISMISSED
    created_at   timestamptz  not null default now(),
    resolved_at  timestamptz
);
create index idx_suggestions_user_status on suggestions (user_id, status);

-- ── notification_logs — 알림 발송 기록 ───────────────────────────────
create table notification_logs (
    id           bigint generated by default as identity primary key,
    user_id      bigint       not null references users (id) on delete cascade,
    type         varchar(20)  not null,                                        -- PAYDAY / ENVELOPE_DUE / CHECK_IN / MATURITY ...
    target_date  date         not null,
    channel      varchar(10)  not null,                                        -- EMAIL / WEB_PUSH / FCM
    sent_at      timestamptz  not null default now(),
    constraint uq_notification_logs unique (user_id, type, target_date)        -- 중복 발송 차단(NOTI-04)
);

-- ── holidays — 공휴일 캐시 (전역, 사용자 무관) ─────────────────────────
create table holidays (
    id            bigint generated by default as identity primary key,
    holiday_date  date         not null,
    name          varchar(50)  not null,
    source_year   smallint     not null,
    constraint uq_holidays_date unique (holiday_date)
);
