-- V2__reminders.sql — 점검 리마인더(NOTI-06): 메모 기반 사용자 정의 리마인더 저장소.
-- 정본: docs/ERD.md(reminders 테이블 추가). 비즈니스 날짜는 date(KST 판정), 저장 시각은 timestamptz.
-- 분기 1회 외화 예수금 점검은 저장 없는 계산형 판정(QuarterlyCheckup)이라 이 테이블을 쓰지 않는다.
-- 마이그레이션 불변: 이 파일은 수정 금지 — 변경은 새 V{n} 추가로만(ADR-08).

-- ── reminders — 사용자 정의 리마인더 ──────────────────────────────────
create table reminders (
    id                bigint generated by default as identity primary key,
    user_id           bigint       not null references users (id) on delete cascade,
    label             varchar(100) not null,                                    -- 사용자 메모(문구는 이 데이터로 클라가 조립)
    interval_months   smallint     not null,                                    -- 사용자 정의 주기(개월). 1 이상
    next_remind_date  date         not null,                                    -- 다음 알림일(KST)
    status            varchar(20)  not null,                                    -- ACTIVE / DELETED (soft delete, 규칙 5)
    created_at        timestamptz  not null default now()
);
create index idx_reminders_user_status on reminders (user_id, status);
